#ifndef TP_PROJECT_FIODORKOLOTILIN_UILOGIC_MAINMENU_H_
#define TP_PROJECT_FIODORKOLOTILIN_UILOGIC_MAINMENU_H_

#include "Widget.h"

class MainMenu : public Widget {

};

#endif //TP_PROJECT_FIODORKOLOTILIN_UILOGIC_MAINMENU_H_
