//
// Created by fedorkolotilin on 13.03.24.
//

#ifndef TP_PROJECT_FIODORKOLOTILIN_UILOGIC_SETTINGS_H_
#define TP_PROJECT_FIODORKOLOTILIN_UILOGIC_SETTINGS_H_

class Settings {

};

#endif //TP_PROJECT_FIODORKOLOTILIN_UILOGIC_SETTINGS_H_
