//
// Created by fedorkolotilin on 13.03.24.
//

#ifndef TP_PROJECT_FIODORKOLOTILIN_UILOGIC_HUB_STARTACTIVITY_H_
#define TP_PROJECT_FIODORKOLOTILIN_UILOGIC_HUB_STARTACTIVITY_H_

class StartActivity {

};

#endif //TP_PROJECT_FIODORKOLOTILIN_UILOGIC_HUB_STARTACTIVITY_H_
