//
// Created by fedorkolotilin on 13.03.24.
//

#ifndef TP_PROJECT_FIODORKOLOTILIN_UILOGIC_GAME_GAMEACTIVITY_H_
#define TP_PROJECT_FIODORKOLOTILIN_UILOGIC_GAME_GAMEACTIVITY_H_

class GameActivity {

};

#endif //TP_PROJECT_FIODORKOLOTILIN_UILOGIC_GAME_GAMEACTIVITY_H_
