//
// Created by fedorkolotilin on 13.03.24.
//

#ifndef TP_PROJECT_FIODORKOLOTILIN_UILOGIC_GAME_GAMEINFOWIDGET_H_
#define TP_PROJECT_FIODORKOLOTILIN_UILOGIC_GAME_GAMEINFOWIDGET_H_

class GameInfoWidget {

};

#endif //TP_PROJECT_FIODORKOLOTILIN_UILOGIC_GAME_GAMEINFOWIDGET_H_
