//
// Created by fedorkolotilin on 19.04.24.
//

#ifndef TP_PROJECT_FIODORKOLOTILIN_HEADERS_UILOGIC_GAME_ROOMSETTINGSWIDGET_H_
#define TP_PROJECT_FIODORKOLOTILIN_HEADERS_UILOGIC_GAME_ROOMSETTINGSWIDGET_H_

#endif //TP_PROJECT_FIODORKOLOTILIN_HEADERS_UILOGIC_GAME_ROOMSETTINGSWIDGET_H_
