//
// Created by fedorkolotilin on 13.03.24.
//

#ifndef TP_PROJECT_FIODORKOLOTILIN_UICLASSES_ACTIVITY_H_
#define TP_PROJECT_FIODORKOLOTILIN_UICLASSES_ACTIVITY_H_

class Activity {

};

#endif //TP_PROJECT_FIODORKOLOTILIN_UICLASSES_ACTIVITY_H_
