//
// Created by fedorkolotilin on 13.03.24.
//

#ifndef TP_PROJECT_FIODORKOLOTILIN_HEADERS_MODEL_APPDATA_DATAMANAGER_H_
#define TP_PROJECT_FIODORKOLOTILIN_HEADERS_MODEL_APPDATA_DATAMANAGER_H_

#endif //TP_PROJECT_FIODORKOLOTILIN_HEADERS_MODEL_APPDATA_DATAMANAGER_H_