//
// Created by fedorkolotilin on 05.04.24.
//

#ifndef TP_PROJECT_FIODORKOLOTILIN_HEADERS_MODEL_GAME_EDGEVIEW_H_
#define TP_PROJECT_FIODORKOLOTILIN_HEADERS_MODEL_GAME_EDGEVIEW_H_

#endif //TP_PROJECT_FIODORKOLOTILIN_HEADERS_MODEL_GAME_EDGEVIEW_H_
