//
// Created by fedorkolotilin on 05.04.24.
//

#ifndef TP_PROJECT_FIODORKOLOTILIN_HEADERS_MODEL_GAME_VERTEXVIEW_H_
#define TP_PROJECT_FIODORKOLOTILIN_HEADERS_MODEL_GAME_VERTEXVIEW_H_

class VertexView {
  
};

#endif //TP_PROJECT_FIODORKOLOTILIN_HEADERS_MODEL_GAME_VERTEXVIEW_H_
