//
// Created by fedorkolotilin on 13.03.24.
//

#ifndef TP_PROJECT_FIODORKOLOTILIN_UICLASSES_WIDGET_H_
#define TP_PROJECT_FIODORKOLOTILIN_UICLASSES_WIDGET_H_

#endif //TP_PROJECT_FIODORKOLOTILIN_UICLASSES_WIDGET_H_
